### PR TITLE
Update fork to upstream/master

### PR DESCRIPTION
**Pull request by NeroBurner**
All changes from the hunter fork at v0.3.4-p1 have been merged. Please merge and release a Version v0.3.4-p2

a notable change is the replacement of the target `glog` with the imported target `glog::glog`.

This PR is in preparation of adding [ceres-solver](https://github.com/ceres-solver/ceres-solver) v1.12.0 to hunter. The latest ceres-solver uses the target `glog::glog`.

### CODE REVIEW

**Comment by ruslo** [comment]
> All changes from the hunter fork at v0.3.4-p1 have been merged. Please merge and release a Version v0.3.4-p2

@NeroBurner can you clarify. `master` to `master` should not contain any "hunter-packages" stuff hence I should not release `v0.3.4-p2` - it should be exactly `v0.3.4` of upstream.

**Comment by NeroBurner** [comment]
`v0.3.4` was already released upstream. The hunter packages `v0.3.4-p0` and `v0.3.4-p1` have been based on that. Unfortunately there is no more recent release than `v0.3.4` upstream. But without release I can't make a downloadable release for hunter. Thats why I suggest a `v0.3.4-p2` release

**Comment by ruslo** [comment]
@NeroBurner If this is `master` to `master` move then I should not release anything after merge. If you want to update branch `hunter` and do release you should open separate pull request for it. Is my understanding of situation is correct?

**Comment by NeroBurner** [comment]
I think you are right. When I follow your advice the branches `hunter` and `master` would be at the same commit, and the hunter release `v0.3.4-p2` would also be at the same commit

**Comment by ruslo** [comment]
@NeroBurner Should I merge this one? Is it "clean" `master` to `master` merge?

**Comment by NeroBurner** [comment]
Yes it is a clean `upstream/master` to `origin/master` merge. It certainly would not hurt, just keeps this branch up to date, and people cloning this repo can see, that `v0.3.4-p2` is just a release of master without modifications

**Pull request merged**
